pipeline {
    agent any

    tools {
        nodejs 'node-20'
    }

    stages {
        stage("Clean Up") {
            steps {
                echo "Cleaning workspace..."
                deleteDir()
                checkout scm
            }
        }

        stage("Install Dependencies") {
            steps {
                dir("backend") {
                    echo "Installing yarn packages..."
                    sh 'corepack enable'
                    sh 'yarn install'
                }
            }
        }

        stage("Test") {
            steps {
                dir("backend") {
                    echo "Running unit tests..."
                    sh 'yarn test'
                }
            }
        }

        stage("Build") {
            steps {
                dir("backend") {
                    echo "Building application..."
                    sh "yarn build"
                }
            }
        }

        stage("Docker Image") {
            steps {
                dir("backend") {
                    echo "Building Docker image..."
                    sh 'docker build -t backend .'
                    sh 'docker rmi backend'
                }
            }
        }
    }

    post {
        always {
            echo "Pipeline finished. Cleaning up..."
        }
        success {
            echo "Deployment successfully!"
        }
        failure {
            echo "Pipeline failed. Check the logs above"
        }
    }
}